# Site settings
title: These are records of Tung Pham's DevOps
url: "https://tunglouis.github.io"    # the protocol and hostname of your site, eg. `https://tunglouis.github.io`
#timezone: Asia/Ho_Chi_Minh
description: >
  One or more sentences introducing this blog.

# Your information
email: tungpv
author: Tung Pham
avatar: "https://s.gravatar.com/avatar/e6ce8d710a132daf5acfd9d67a133dbf?s=80"
profile: One sentence introducing yourself.
#twitter_username: twitter_username
#github_username:  github_username
profile_links:
  Email: "mailto:tungpv.it@gmail.com"
  GitHub: "https://github.com/tunglouis/"
  # You can add more profile links above, or edit _includes/sidebar.html 

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

excerpt_separator: <!--more-->

header:
  links:             # Links on the header. Link to in-site page with a slash as prefix
    About: /about/
    Category: /category/
    Donate: https://tunglouis.github.io/

permalink: /archivers/:title
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

# https://jekyllrb.com/docs/configuration/#precedence
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
